CREATE TABLE "STUDENT"(
   "ID" int NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   "NAME" varchar(60) NOT NULL,
   "SURNAME" varchar(60) NOT NULL,
   "BORN_DATE" DATE NOT NULL,
   "SEX" varchar(4) NOT NULL  
);
